global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  - job_name: packops
    metrics_path: /probe
    params:
      module:
        - http_2xx
    scrape_interval: 30s
    static_configs:
      - targets:
          - https://packops.ir
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: asd
    metrics_path: /probe
    params:
      module:
        - http_2xx
    scrape_interval: 30s
    static_configs:
      - targets:
          - https://asdas.asdas.com
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
  - job_name: google
    metrics_path: /probe
    params:
      module:
        - http_2xx
    scrape_interval: 30s
    static_configs:
      - targets:
          - 8.8.8.8
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
